name: matchup
description: "A new Flutter project."

publish_to: 'none'

version: 1.0.0+1

environment:
  # sdk: '>=3.3.0 <4.0.0'
  sdk: ">=2.17.0 <3.0.0"


dependencies:
  flutter: 
    sdk: flutter
  table_calendar: ^3.0.9
  camera: ^0.11.0
  path_provider: ^2.1.2
  path: ^1.7.0
  fl_chart: ^0.67.0
  font_awesome_flutter: ^10.7.0
  http: ^1.2.1
  flutter_config: any
  http_parser: ^4.0.0
  provider: ^6.0.2
  photo_view: ^0.15.0
  web_socket_channel: ^2.1.0
  google_mlkit_commons: ^0.3.0
  google_mlkit_pose_detection: ^0.6.0
  lifecycle: ^0.8.0
  flutter_tts: ^4.0.2
  video_player: ^2.8.6

  cupertino_icons: ^1.0.6

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^3.0.0

flutter:

  uses-material-design: true
  assets:
  - lib/assets/images/
  - lib/screens/
  - lib/assets/fonts/
  - lib/assets/video/
  - lib/assets/video/lunge.mp4
  - lib/assets/video/squat.mp4
  - lib/assets/video/waist.mp4

  fonts:
    - family: Timmana
      fonts:
        - asset: lib/assets/fonts/Timmana-Regular.ttf
          weight: 200